[WIP] System container support
openshift/playbook2image pull request #3
Opened 2017-05-03 17:14 UTC by codificat

Add files and documentation to support running images built from playbook2image to be run as system containers.

One of the changes (avoid `/etc/passwd` update for `root`) is kind of independent, but it is specially relevant to this use case because normal usage is expected to run under non-root.

WIP because it's probably worth waiting for a release of `atomic` that includes https://github.com/projectatomic/atomic/pull/952 and to add the corresponding label, test and update the docs. Feedback is welcome meanwhile :)

2017-05-26 13:40 UTC, aweiteka requested changes
Great to see this capability added. Can you mention the use case in this README? Why would I choose to use a system container vs running a container manually?

2017-05-26 13:40 UTC, aweiteka commented on system-container/README.md
> +A system container runs using runC instead of Docker and it is managed by the
Maybe better to say the process is managed by systemd and installed using the atomic tool.

2017-05-26 13:40 UTC, aweiteka commented on system-container/README.md
> +Once a container image is built (e.g. `my/image`) you can import it into the OSTree storage:
Let's remind or clarify that this build step is where the user adds their playbooks to the base image.

2017-05-26 13:40 UTC, aweiteka commented on system-container/README.md
> +*NOTE:* after the next release of the `atomic` command that includes [PR 952](https://github.com/projectatomic/atomic/pull/952) we will add an `atomic.run=once` label and the `systemctl` invocation o
PR#952 has been merged.

2017-05-26 13:40 UTC, aweiteka commented on system-container/README.md
> +If the playbooks need additional files then they can use the path `/var/lib/playbook2image` in the container as it is bind mounted from the host (the source directory is controllable with `VAR_LIB_PL
Is there a default host path you can call out here?

2017-05-31 11:10 UTC, codificat commented on system-container/README.md
> +A system container runs using runC instead of Docker and it is managed by the
I believe systemd is not involved in the "run once" scenario

2017-05-31 11:11 UTC, codificat commented on system-container/README.md
> +Once a container image is built (e.g. `my/image`) you can import it into the OSTree storage:
Right, will clean up this a bit more - I took this content from contributed docs to the openshift-ansible repo and it's indeed worth customizing a bit more for playbook2image...

2017-05-31 11:13 UTC, codificat commented on system-container/README.md
> +*NOTE:* after the next release of the `atomic` command that includes [PR 952](https://github.com/projectatomic/atomic/pull/952) we will add an `atomic.run=once` label and the `systemctl` invocation o
Yes it was, but just recently (last week) there was a release of the `atomic` tool with the changes.

Now that this is actually available I will do some actual testing :) and update

2017-06-13 17:40 UTC, codificat commented
@aweiteka I expanded the docs a bit more with your feedback.

Also added the `atomic.run="once"` label for the system container use case. I believe that for system containers coming from playbook2image we will always want to use that *run once* approach. What do you think? Is there a use case where we'd prefer systemd to manage the execution of the playbook instead? If so, should we then document how to remove that label in the `docker build`-based docs, or should we instead not add the label by default and document how to add it?

2017-06-13 18:45 UTC, aweiteka approved these changes

2017-06-13 18:46 UTC, aweiteka commented
> What do you think? Is there a use case where we'd prefer systemd to manage the execution of the playbook instead?

I think it's fine as-is right now. We can get this in and get user feedback.

Is it okay with you to merge?

2017-06-13 20:45 UTC, codificat commented
LGTM, ship it!

2017-06-14 15:16 UTC, merged